<Project>
  <PropertyGroup>
    <GameDir Condition="'$(GameDir)' == ''">$(SWYF_GAME_DIR)</GameDir>
    <GameManaged>$(GameDir)\Scam With Your Friends_Data\Managed</GameManaged>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildThisFileDirectory)=/_/</PathMap>
  </PropertyGroup>
</Project>
