<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SwyfInstallerGui</AssemblyName>
    <Version>1.1.0</Version>
    <Description>Basic UI for the SWYF Custom AI installer.</Description>
  </PropertyGroup>

</Project>
